services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      POSTGRES_DB: useful-tools
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psswrd
    networks:
      - development-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: psswrd
    depends_on:
      - postgres
    networks:
      - development-network

  app:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports: 
      - 3000:3000
    networks:
      - development-network

networks:
  development-network:
    driver: bridge